name: Terraform Dev CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
jobs:
  terraform-plan:
    name: Dev - Terraform Validate & Plan
    runs-on: self-hosted
    defaults:
      run:
        working-directory: C:\Agent\actions-runner\_work\terraform-azure-github-actions\terraform-azure-github-actions\Enviroments\dev
        shell: powershell
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Verify Azure Login
        shell: powershell
        run: |
          Write-Host "Checking Azure Login..."
          az account show
          
      - name: Terraform Version
        run: |
          terraform version
          
      - name: Terraform Init
        run: |
          terraform init
      - name: Terraform Validate
        run: |
          terraform validate

  tfsec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: C:\Agent\actions-runner\_work\terraform-azure-github-actions\terraform-azure-github-actions\Enviroments\dev


      - name: Terraform Plan
        run: |
          Write-Host "Current Directory:"
          Get-Location
          Write-Host "Running Terraform Plan..."

          terraform plan -out=tfplan

          Write-Host "Checking tfplan..."

          if (Test-Path ".\tfplan") {
              Write-Host "SUCCESS: tfplan created."
              Get-Item ".\tfplan"
          }
          else {
              Write-Error "ERROR: tfplan was not created."
              exit 1
          }
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-dev-plan
          path: Enviroments/dev/tfplan
          if-no-files-found: error

  terraform-apply:
    name: Dev - Terraform Apply
    needs: terraform-plan
    runs-on: self-hosted

    environment:
      name: dev

    defaults:
      run:
        working-directory: C:\Agent\actions-runner\_work\terraform-azure-github-actions\terraform-azure-github-actions\Enviroments\dev
        shell: powershell

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Verify Azure Login
        shell: powershell
        run: |
          Write-Host "Checking Azure Login..."
          az account show
          
      - name: Terraform Version
        run: |
          terraform version
          
      - name: Terraform Init
        run: |
          terraform init
          
      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-dev-plan
          path: Enviroments/dev

      - name: Verify Terraform Plan
        run: |
          Write-Host "Current Directory:"
          Get-Location

          Write-Host "Checking downloaded tfplan..."

          if (Test-Path ".\tfplan") {
              Write-Host "SUCCESS: tfplan downloaded."
              Get-Item ".\tfplan"
          }
          else {
              Write-Error "ERROR: tfplan not found."
              exit 1
          }
      - name: Terraform Apply
        run: |
          Write-Host "Applying Terraform Plan..."

          terraform apply -auto-approve tfplan
